/**
 * Tests for src/io/sql.ts — readSql, readSqlQuery, readSqlTable, toSql.
 *
 * Uses an in-memory MockAdapter that stores tables as arrays of row objects so
 * all functionality can be exercised without an external database.
 */
import { describe, expect, it } from "bun:test";
import fc from "fast-check";
import { DataFrame, readSql, readSqlQuery, readSqlTable, toSql } from "../../src/index.ts";
import type {
  IfExistsStrategy,
  SqlConnection,
  SqlResult,
  SqlRow,
  SqlValue,
} from "../../src/index.ts";
import { TableExistsError, TableNotFoundError } from "../../src/index.ts";

// ─── MockAdapter ──────────────────────────────────────────────────────────────

/**
 * Minimal in-memory SQL adapter for testing.
 *
 * Supports:
 * - `SELECT * FROM "<table>"` (exact pattern generated by readSqlTable)
 * - `SELECT col1, col2 FROM "<table>"` (column projection)
 * - `INSERT INTO "<table>" (...) VALUES (...)` (single-row inserts)
 * - `DROP TABLE IF EXISTS "<table>"`
 * - `listTables()` and `insert()` adapter methods
 */
class MockAdapter implements SqlConnection {
  private readonly tables: Map<string, SqlRow[]> = new Map();
  private readonly schemas: Map<string, string[]> = new Map();

  /** Seed a table with pre-existing data. */
  seed(name: string, rows: SqlRow[]): void {
    this.tables.set(
      name,
      rows.map((r) => ({ ...r })),
    );
    if (rows.length > 0) {
      const first = rows[0];
      if (first !== undefined) {
        this.schemas.set(name, Object.keys(first));
      }
    }
  }

  query(sql: string): SqlResult {
    const trimmed = sql.trim();

    // DROP TABLE IF EXISTS "<name>"
    const dropMatch = /^DROP TABLE IF EXISTS "(.+)"$/i.exec(trimmed);
    if (dropMatch !== null) {
      const name = dropMatch[1];
      if (name !== undefined) {
        this.tables.delete(name);
        this.schemas.delete(name);
      }
      return { columns: [], rows: [] };
    }

    // INSERT INTO "<name>" (col, …) VALUES (val, …)
    const insertMatch = /^INSERT INTO "(.+)" \((.+)\) VALUES \((.+)\)$/i.exec(trimmed);
    if (insertMatch !== null) {
      const [, rawName, rawCols, rawVals] = insertMatch;
      if (rawName !== undefined && rawCols !== undefined && rawVals !== undefined) {
        const cols = rawCols.split(",").map((c) => c.trim().replace(/^"|"$/g, ""));
        const vals = parseValueList(rawVals);
        const row: SqlRow = {};
        for (let i = 0; i < cols.length; i++) {
          const col = cols[i];
          const val = vals[i];
          if (col !== undefined && val !== undefined) {
            row[col] = val;
          }
        }
        const existing = this.tables.get(rawName);
        if (existing !== undefined) {
          existing.push(row);
        } else {
          this.tables.set(rawName, [row]);
        }
        if (!this.schemas.has(rawName)) {
          this.schemas.set(rawName, cols);
        }
      }
      return { columns: [], rows: [] };
    }

    // SELECT … FROM "<name>"
    const selectMatch = /^SELECT\s+(.+?)\s+FROM\s+"([^"]+)"(?:\s*$)/i.exec(trimmed);
    if (selectMatch !== null) {
      const [, selectCols, rawName] = selectMatch;
      if (rawName !== undefined && selectCols !== undefined) {
        const rows = this.tables.get(rawName) ?? [];
        const allCols = this.schemas.get(rawName) ?? (rows.length > 0 ? Object.keys(rows[0]!) : []);
        const wantedCols =
          selectCols.trim() === "*"
            ? allCols
            : selectCols.split(",").map((c) => c.trim().replace(/^"|"$/g, ""));
        const resultRows: SqlRow[] = rows.map((r) => {
          const out: SqlRow = {};
          for (const col of wantedCols) {
            out[col] = r[col] ?? null;
          }
          return out;
        });
        return { columns: wantedCols, rows: resultRows };
      }
    }

    return { columns: [], rows: [] };
  }

  listTables(): readonly string[] {
    return [...this.tables.keys()];
  }

  insert(
    tableName: string,
    rows: readonly SqlRow[],
    columns: readonly string[],
    ifExists: IfExistsStrategy,
  ): number {
    const existing = this.tables.get(tableName);
    if (existing !== undefined) {
      if (ifExists === "fail") {
        throw new TableExistsError(tableName);
      }
      if (ifExists === "replace") {
        this.tables.delete(tableName);
        this.schemas.delete(tableName);
      }
    }
    const arr = this.tables.get(tableName) ?? [];
    for (const row of rows) {
      arr.push({ ...row });
    }
    this.tables.set(tableName, arr);
    this.schemas.set(tableName, [...columns]);
    return rows.length;
  }

  /** Expose stored rows for assertions. */
  getRows(name: string): SqlRow[] {
    return this.tables.get(name) ?? [];
  }
}

// ─── SQL literal parser for mock INSERT handling ──────────────────────────────

function parseValueList(raw: string): SqlValue[] {
  const values: SqlValue[] = [];
  let i = 0;

  while (i < raw.length) {
    while (i < raw.length && raw[i] === " ") i++;
    if (i >= raw.length) break;

    const ch = raw[i];
    if (ch === undefined) break;

    if (ch === "N" && raw.slice(i, i + 4) === "NULL") {
      values.push(null);
      i += 4;
    } else if (ch === "'") {
      // String literal
      i++; // skip opening quote
      let s = "";
      while (i < raw.length) {
        const c = raw[i];
        if (c === "'") {
          if (raw[i + 1] === "'") {
            s += "'";
            i += 2;
          } else {
            i++;
            break;
          }
        } else {
          s += c ?? "";
          i++;
        }
      }
      values.push(s);
    } else if (ch === "X" && raw[i + 1] === "'") {
      // Hex blob: X'deadbeef'
      i += 2;
      let hex = "";
      while (i < raw.length && raw[i] !== "'") {
        hex += raw[i];
        i++;
      }
      i++; // skip closing quote
      const bytes = new Uint8Array(hex.length / 2);
      for (let b = 0; b < bytes.length; b++) {
        bytes[b] = Number.parseInt(hex.slice(b * 2, b * 2 + 2), 16);
      }
      values.push(bytes);
    } else {
      // Number
      let numStr = "";
      while (i < raw.length && raw[i] !== "," && raw[i] !== " ") {
        numStr += raw[i];
        i++;
      }
      const n = Number(numStr);
      values.push(Number.isNaN(n) ? numStr : n);
    }

    while (i < raw.length && raw[i] === " ") i++;
    if (raw[i] === ",") i++;
  }

  return values;
}

// ─── readSqlQuery ─────────────────────────────────────────────────────────────

describe("readSqlQuery — basic", () => {
  it("returns a DataFrame with correct shape and values", () => {
    const db = new MockAdapter();
    db.seed("users", [
      { id: 1, name: "Alice", score: 9.5 },
      { id: 2, name: "Bob", score: 7.0 },
    ]);
    const df = readSqlQuery('SELECT * FROM "users"', db);
    expect(df.shape).toEqual([2, 3]);
    expect([...df.columns.values]).toEqual(["id", "name", "score"]);
    expect([...df.col("id").values]).toEqual([1, 2]);
    expect([...df.col("name").values]).toEqual(["Alice", "Bob"]);
  });

  it("respects indexCol (string)", () => {
    const db = new MockAdapter();
    db.seed("t", [
      { id: 10, val: "a" },
      { id: 20, val: "b" },
    ]);
    const df = readSqlQuery('SELECT * FROM "t"', db, { indexCol: "id" });
    expect(df.shape).toEqual([2, 1]);
    expect([...df.columns.values]).toEqual(["val"]);
    expect([...df.index.values]).toEqual([10, 20]);
    expect(df.index.name).toBe("id");
  });

  it("respects indexCol (number)", () => {
    const db = new MockAdapter();
    db.seed("t", [{ id: 5, x: 1 }]);
    const df = readSqlQuery('SELECT * FROM "t"', db, { indexCol: 0 });
    expect([...df.index.values]).toEqual([5]);
  });

  it("parses date columns", () => {
    const db = new MockAdapter();
    db.seed("events", [{ dt: "2024-01-01", val: 1 }]);
    const df = readSqlQuery('SELECT * FROM "events"', db, {
      parseDates: ["dt"],
    });
    const dtVal = df.col("dt").values[0];
    expect(typeof dtVal).toBe("number");
    const d = new Date(dtVal as number);
    expect(d.getUTCFullYear()).toBe(2024);
  });

  it("null values stay null", () => {
    const db = new MockAdapter();
    db.seed("t", [{ x: null }]);
    const df = readSqlQuery('SELECT * FROM "t"', db);
    expect(df.col("x").values[0]).toBeNull();
  });

  it("returns empty DataFrame for empty result", () => {
    const db = new MockAdapter();
    const result: SqlResult = { columns: ["a", "b"], rows: [] };
    const df = readSqlQuery("SELECT a, b FROM empty_table", {
      query() {
        return result;
      },
    });
    expect(df.shape).toEqual([0, 2]);
    expect([...df.columns.values]).toEqual(["a", "b"]);
  });
});

// ─── readSqlTable ─────────────────────────────────────────────────────────────

describe("readSqlTable — basic", () => {
  it("reads entire table", () => {
    const db = new MockAdapter();
    db.seed("products", [
      { id: 1, name: "Widget", price: 9.99 },
      { id: 2, name: "Gadget", price: 24.99 },
    ]);
    const df = readSqlTable("products", db);
    expect(df.shape).toEqual([2, 3]);
    expect([...df.col("price").values]).toEqual([9.99, 24.99]);
  });

  it("projects requested columns", () => {
    const db = new MockAdapter();
    db.seed("products", [{ id: 1, name: "W", price: 1 }]);
    const df = readSqlTable("products", db, { columns: ["id", "name"] });
    expect([...df.columns.values]).toEqual(["id", "name"]);
    expect(df.shape).toEqual([1, 2]);
  });

  it("throws TableNotFoundError for unknown table", () => {
    const db = new MockAdapter();
    expect(() => readSqlTable("missing", db)).toThrow(TableNotFoundError);
  });

  it("does not validate when listTables is absent", () => {
    const minimalConn: SqlConnection = {
      query(): SqlResult {
        return { columns: ["x"], rows: [{ x: 1 }] };
      },
    };
    const df = readSqlTable("any_table", minimalConn);
    expect(df.shape).toEqual([1, 1]);
  });
});

// ─── readSql ──────────────────────────────────────────────────────────────────

describe("readSql — auto-detect", () => {
  it("detects SQL query by whitespace", () => {
    const db = new MockAdapter();
    db.seed("orders", [{ id: 1, amount: 100 }]);
    const df = readSql('SELECT id, amount FROM "orders"', db);
    expect(df.shape).toEqual([1, 2]);
  });

  it("detects table name (no whitespace)", () => {
    const db = new MockAdapter();
    db.seed("orders", [{ id: 1 }, { id: 2 }]);
    const df = readSql("orders", db);
    expect(df.shape).toEqual([2, 1]);
  });
});

// ─── toSql ────────────────────────────────────────────────────────────────────

describe("toSql — basic", () => {
  it("writes all rows and returns count", () => {
    const db = new MockAdapter();
    const df = DataFrame.fromColumns({
      name: ["Alice", "Bob"],
      score: [100, 90],
    });
    const written = toSql(df, "results", db);
    expect(written).toBe(2);
    const stored = db.getRows("results");
    expect(stored).toHaveLength(2);
  });

  it("writes index column when index: true (default)", () => {
    const db = new MockAdapter();
    const df = DataFrame.fromColumns({ x: [10, 20] });
    toSql(df, "t", db, { index: true });
    const rows = db.getRows("t");
    expect(rows[0]).toHaveProperty("index");
    expect(rows[0]!["index"]).toBe(0);
  });

  it("omits index column when index: false", () => {
    const db = new MockAdapter();
    const df = DataFrame.fromColumns({ x: [1, 2] });
    toSql(df, "t", db, { index: false });
    const rows = db.getRows("t");
    expect(rows[0]).not.toHaveProperty("index");
    expect(rows[0]).toHaveProperty("x");
  });

  it("respects custom indexLabel", () => {
    const db = new MockAdapter();
    const df = DataFrame.fromColumns({ v: [99] });
    toSql(df, "t", db, { indexLabel: "row_id" });
    expect(db.getRows("t")[0]).toHaveProperty("row_id");
  });

  it("ifExists: fail throws when table exists", () => {
    const db = new MockAdapter();
    db.seed("t", [{ x: 1 }]);
    const df = DataFrame.fromColumns({ x: [2] });
    expect(() => toSql(df, "t", db, { ifExists: "fail" })).toThrow(TableExistsError);
  });

  it("ifExists: replace overwrites data", () => {
    const db = new MockAdapter();
    db.seed("t", [{ x: 1 }, { x: 2 }]);
    const df = DataFrame.fromColumns({ x: [99] });
    toSql(df, "t", db, { ifExists: "replace", index: false });
    const rows = db.getRows("t");
    expect(rows).toHaveLength(1);
    expect(rows[0]!["x"]).toBe(99);
  });

  it("ifExists: append adds to existing data", () => {
    const db = new MockAdapter();
    db.seed("t", [{ x: 1 }]);
    const df = DataFrame.fromColumns({ x: [2, 3] });
    toSql(df, "t", db, { ifExists: "append", index: false });
    const rows = db.getRows("t");
    expect(rows).toHaveLength(3);
  });

  it("returns 0 rows for empty DataFrame", () => {
    const db = new MockAdapter();
    const df = DataFrame.fromColumns({ x: [] as number[] });
    const n = toSql(df, "empty", db, { index: false });
    expect(n).toBe(0);
  });
});

// ─── toSql fallback (query-only adapter) ─────────────────────────────────────

describe("toSql — fallback path (no insert method)", () => {
  it("writes rows via INSERT statements", () => {
    const inserted: string[] = [];
    const queryConn: SqlConnection = {
      query(sql: string): SqlResult {
        inserted.push(sql);
        return { columns: [], rows: [] };
      },
    };
    const df = DataFrame.fromColumns({ a: [1, 2], b: ["x", "y"] });
    const n = toSql(df, "dest", queryConn, { index: false });
    expect(n).toBe(2);
    expect(inserted.some((s) => /INSERT INTO/.test(s))).toBe(true);
  });

  it("chunksize controls batch grouping", () => {
    const calls: string[] = [];
    const queryConn: SqlConnection = {
      query(sql: string): SqlResult {
        calls.push(sql);
        return { columns: [], rows: [] };
      },
    };
    const df = DataFrame.fromColumns({ v: [1, 2, 3, 4, 5] });
    toSql(df, "t", queryConn, { index: false, chunksize: 2 });
    const inserts = calls.filter((s) => /INSERT INTO/.test(s));
    expect(inserts).toHaveLength(5);
  });

  it("handles null scalar values", () => {
    const sqls: string[] = [];
    const queryConn: SqlConnection = {
      query(sql: string): SqlResult {
        sqls.push(sql);
        return { columns: [], rows: [] };
      },
    };
    const df = DataFrame.fromColumns({ x: [null] });
    toSql(df, "t", queryConn, { index: false });
    expect(sqls.some((s) => s.includes("NULL"))).toBe(true);
  });
});

// ─── round-trip ───────────────────────────────────────────────────────────────

describe("toSql / readSqlTable — round-trip", () => {
  it("numeric data survives a round-trip", () => {
    const db = new MockAdapter();
    const original = DataFrame.fromColumns({
      a: [1, 2, 3],
      b: [0.1, 0.2, 0.3],
    });
    toSql(original, "data", db, { index: false });
    const restored = readSqlTable("data", db);
    expect(restored.shape).toEqual([3, 2]);
    expect([...restored.col("a").values]).toEqual([1, 2, 3]);
    expect([...restored.col("b").values]).toEqual([0.1, 0.2, 0.3]);
  });

  it("string data survives a round-trip", () => {
    const db = new MockAdapter();
    const original = DataFrame.fromColumns({ name: ["Alice", "Bob"] });
    toSql(original, "names", db, { index: false });
    const restored = readSqlTable("names", db);
    expect([...restored.col("name").values]).toEqual(["Alice", "Bob"]);
  });

  it("boolean data survives a round-trip via fallback path", () => {
    const rows: SqlRow[] = [];
    let dropCalled = false;
    const fakeConn: SqlConnection = {
      query(sql: string): SqlResult {
        if (/^DROP/i.test(sql)) {
          dropCalled = true;
          rows.length = 0;
          return { columns: [], rows: [] };
        }
        if (/^INSERT/i.test(sql)) {
          // Parse the boolean-like values out for assertion
          rows.push({ _sql: sql });
          return { columns: [], rows: [] };
        }
        return { columns: ["flag"], rows };
      },
    };
    const df = DataFrame.fromColumns({ flag: [true, false] });
    toSql(df, "t", fakeConn, { index: false, ifExists: "replace" });
    expect(dropCalled).toBe(true);
    expect(rows).toHaveLength(2);
  });
});

// ─── property-based tests ─────────────────────────────────────────────────────

describe("readSqlQuery — property tests", () => {
  it("shape matches result column/row counts", () => {
    fc.assert(
      fc.property(
        fc.array(fc.string({ minLength: 1, maxLength: 10 }), {
          minLength: 1,
          maxLength: 5,
        }),
        fc.integer({ min: 0, max: 20 }),
        (cols, rowCount) => {
          const uniqueCols = [...new Set(cols)];
          if (uniqueCols.length === 0) return;
          const rows: SqlRow[] = Array.from({ length: rowCount }, () => {
            const row: SqlRow = {};
            for (const c of uniqueCols) {
              row[c] = 42;
            }
            return row;
          });
          const result: SqlResult = { columns: uniqueCols, rows };
          const conn: SqlConnection = { query: () => result };
          const df = readSqlQuery("SELECT 1", conn);
          expect(df.shape).toEqual([rowCount, uniqueCols.length]);
        },
      ),
    );
  });
});

describe("toSql — property tests", () => {
  it("round-trip preserves number of rows (adapter path)", () => {
    fc.assert(
      fc.property(
        fc.array(fc.double({ noNaN: true, noDefaultInfinity: true }), {
          minLength: 0,
          maxLength: 30,
        }),
        (vals) => {
          const db = new MockAdapter();
          const df = DataFrame.fromColumns({ v: vals });
          const written = toSql(df, "tbl", db, { index: false });
          expect(written).toBe(vals.length);
          const back = readSqlTable("tbl", db);
          expect(back.shape[0]).toBe(vals.length);
        },
      ),
    );
  });
});
