/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const expanding_max_f64: (a: number, b: number, c: number) => [number, number];
export const expanding_mean_f64: (a: number, b: number, c: number) => [number, number];
export const expanding_median_f64: (a: number, b: number, c: number) => [number, number];
export const expanding_min_f64: (a: number, b: number, c: number) => [number, number];
export const expanding_std_f64: (a: number, b: number, c: number, d: number) => [number, number];
export const expanding_sum_f64: (a: number, b: number, c: number) => [number, number];
export const expanding_var_f64: (a: number, b: number, c: number, d: number) => [number, number];
export const nat_argsort: (a: number, b: number, c: number, d: number) => [number, number];
export const nat_compare: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const nat_sorted: (a: number, b: number, c: number, d: number) => [number, number];
export const rolling_max_f64: (a: number, b: number, c: number, d: number) => [number, number];
export const rolling_mean_f64: (a: number, b: number, c: number, d: number) => [number, number];
export const rolling_median_f64: (a: number, b: number, c: number, d: number) => [number, number];
export const rolling_min_f64: (a: number, b: number, c: number, d: number) => [number, number];
export const rolling_std_f64: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const rolling_sum_f64: (a: number, b: number, c: number, d: number) => [number, number];
export const rolling_var_f64: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const argsort_f64: (a: number, b: number) => [number, number];
export const argsort_str: (a: number, b: number) => [number, number];
export const max_f64: (a: number, b: number) => number;
export const mean_f64: (a: number, b: number) => number;
export const median_f64: (a: number, b: number) => number;
export const min_f64: (a: number, b: number) => number;
export const searchsorted_f64: (a: number, b: number, c: number, d: number) => number;
export const searchsorted_many_f64: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const searchsorted_many_str: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const searchsorted_str: (a: number, b: number, c: number, d: number, e: number) => number;
export const std_f64: (a: number, b: number, c: number) => number;
export const sum_f64: (a: number, b: number) => number;
export const var_f64: (a: number, b: number, c: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_alloc: () => number;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
